<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>de.crashguard</groupId><artifactId>crashguard-parent</artifactId><version>1.0.0-SNAPSHOT</version></parent><artifactId>crashguard-bungeecord</artifactId>
<dependencies><dependency><groupId>de.crashguard</groupId><artifactId>crashguard-common</artifactId><version>${project.version}</version></dependency><dependency><groupId>net.md-5</groupId><artifactId>bungeecord-api</artifactId><version>1.21-R0.3</version><scope>provided</scope></dependency></dependencies>
<build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-shade-plugin</artifactId><version>3.6.0</version><executions><execution><phase>package</phase><goals><goal>shade</goal></goals><configuration><createDependencyReducedPom>false</createDependencyReducedPom><relocations><relocation><pattern>org.yaml.snakeyaml</pattern><shadedPattern>de.crashguard.internal.yaml</shadedPattern></relocation></relocations><filters><filter><artifact>*:*</artifact><excludes><exclude>META-INF/*.SF</exclude><exclude>META-INF/*.RSA</exclude><exclude>META-INF/*.DSA</exclude></excludes></filter></filters></configuration></execution></executions></plugin></plugins></build>
</project>
